### Test GET
GET http://localhost:8080/hello

###

# Test POST user creation
POST http://localhost:8080/user
Content-Type: application/json
Accept: application/json

{
  "id": 1,
  "name": "Khushi"
}

###

# Test GET user by ID
GET http://localhost:8080/user/1

###
# User Not Found exception
GET http://localhost:8080/user/99

###
POST http://localhost:8080/user
Content-Type: application/json
Accept: application/json

{
  "id": 2,
  "name": "Hello"
}

###
PUT http://localhost:8080/user/1
Content-Type: application/json

{
  "name": "New Name"
}

###
DELETE http://localhost:8080/user/1
###
PUT http://localhost:8080/user/3
Content-Type: application/json

{
  "name": "New Name"
}
###
DELETE http://localhost:8080/user/3

###
GET http://localhost:8080/users/search?name=Khus
